language: python
python:
  - "2.7"
    #- "3.3"
install:
  - python setup.py install
  - pip install git+git://github.com/pdxacm/acmapi.git#egg=acmapi
# command to run tests
script: nosetests --with-doctest
notifications:
    irc: "irc.cat.pdx.edu#acm-dev"
